In [119]:
import pandas as pd
import numpy as np
import scipy
from sklearn import preprocessing

In [120]:
data = pd.read_csv("./src/data/AmazonScraped/AmazonProductRatings.csv",header=None)

In [121]:
import implicit


In [122]:
model = implicit.als.AlternatingLeastSquares(factors=10)


In [123]:
data.head()

0               1    2           3
0  B000K2PJ4K  A334KVYM5MMQMR  5.0  1390780800
1  B000K2PJ4K    A9UJRNHH1B6O  1.0  1390435200
2  B000K2PJ4K  A3KAX7T0ZEGVOV  4.0  1389571200
3  B000K2PJ4K   ANICWNHH5DH02  5.0  1389312000
4  B000K2PJ4K  A2UKWG2OM70X63  5.0  1389225600

In [124]:
data = data.drop([3],axis=1)

In [125]:
data.isnull().any()

0    False
1    False
2    False
dtype: bool

In [126]:
data.dtypes

0     object
1     object
2    float64
dtype: object

In [127]:
le1 = preprocessing.LabelEncoder()
le2 = preprocessing.LabelEncoder()
le3 = preprocessing.LabelEncoder()

In [128]:
col1 = np.array(data[0])
col2  = np.array(data[1])
col3  = np.array(data[2]).astype('float')

In [139]:
col2 = le2.fit_transform(col2)
col1 = le1.fit_transform(col1)
col2

array([6329, 9192, 7726, ..., 8907, 5864, 8075])

In [140]:
data_Arr = np.array([col1,col2,col3])

In [141]:
data_Arr.transpose()

array([[0.000e+00, 6.329e+03, 5.000e+00],
       [0.000e+00, 9.192e+03, 1.000e+00],
       [0.000e+00, 7.726e+03, 4.000e+00],
       ...,
       [1.900e+01, 8.907e+03, 5.000e+00],
       [1.900e+01, 5.864e+03, 5.000e+00],
       [1.900e+01, 8.075e+03, 5.000e+00]])

In [142]:
data_Arr

array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 1.900e+01, 1.900e+01,
        1.900e+01],
       [6.329e+03, 9.192e+03, 7.726e+03, ..., 8.907e+03, 5.864e+03,
        8.075e+03],
       [5.000e+00, 1.000e+00, 4.000e+00, ..., 5.000e+00, 5.000e+00,
        5.000e+00]])

In [143]:
data_sparse  = scipy.sparse.coo_matrix(data_Arr)


In [144]:
model.fit(data_sparse)


In [148]:
user_items = data_sparse.T.tocsr()


In [163]:
recommendations = model.recommend(800, user_items)


In [164]:
recommendations

[(0, -0.0030087158)]

In [166]:
related = model.similar_items(2)

ValueError: kth(=-7) out of bounds (3)